# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PesosDolares' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  xcodeproj '/Volumes/Neto/PesosDolares/PesosDolares.xcodeproj'
  # Pods for PesosDolares
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'SwiftKeychainWrapper'
  pod 'Alamofire', '~> 4.0'
  pod 'GeoFire', '~> 1.1'
end
